### ISSUE TITLE
AV in MPShellUtilities initialization under system local account

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/MustangpeakCommonLib#6]
```
Trying to build a windows service that references MPShellUtilities, under my 
system, it seems the initial folder points to a non-existing place and an AV 
happens. To fix it, inside 

function PIDLIsFolder(APIDL: PItemIDList): Boolean;

I have to do this:

  if not Assigned(APIDL) then Exit;

I don't really need anything in that unit for the service, it just happens to 
be shared with a non-used code in the same EXE, but the initialization runs 
anyway
```

Original issue reported on code.google.com by `soler...@gmail.com` on 14 Aug 2013 at 12:36

**Comment by pyscripter** [comment]
Fixed

**Comment by yonojoy** [comment]
I don't think the check implemented in the fix is enough. I get an access violation with following call stack:
        ------------------------------------------------------------------
        |Unit            |Class     |Procedure/Method          |Line     |
        ------------------------------------------------------------------
        |MPShellUtilities|          |PIDLIsFolder              |2160[22] |
        |MPShellUtilities|TNamespace|GetShellFolder            |6432[15] |
        |MPShellUtilities|TNamespace|GetParentShellFolder      |6267[3]  |
        |MPShellUtilities|          |CreateKnownFolderNamespace|3100[13] |
        |MPShellUtilities|          |Initialization            |10965[11]|
        |System          |          |InitUnits                 |         |
        |System          |          |_StartExe                 |         |

The access violation occurs, because `LastPIDL` is nil.

**Comment by pyscripter** [comment]
Are you using the master branch version?  From the line numbers it appears that you are not.  Line 2160 is not inside PIDLIsFolder.

**Comment by yonojoy** [comment]
Sorry, I forgot to mention. I use a fork of the TurboPack fork: https://github.com/yonojoy/MustangpeakCommonLib/commits/ForXE4 (commit e2830f8212ecb58a4550b5c67da30ed03f8cf12d).

The access violation occurs in 

      finally
        if LastPIDL^.mkid.cb = 0 then      //<<<< in this line
          LastPIDL^.mkid.cb := Last_CB;
      end

I submitted a pull request for my origin code base (https://github.com/TurboPack/MustangpeakCommonLib/pull/1) , but also wanted to leave a notice here, because I thought this is the original project.

**Comment by pyscripter** [comment]
Then please file the bug report there.

**Comment by yonojoy** [comment]
This bug is not reproduceable. We got a bug report for one out of maybe 1000 systems in one of maybe 100 calls.
The TurboPack fork does not seem to be a regular fork, so switching is not possible. 
The code base I used did not contain the fix suggested here (`if not Assigned(APIDL) then Exit;`) but I am unsure that it would prevent the access violation for `LastPIDL`.

But I filed a new bug report, as you suggested: https://github.com/pyscripter/MustangpeakCommonLib/issues/11
